services:
  - type: web
    name: fpl-backend
    env: python
    runtime: python311
    buildCommand: "pip install --no-cache-dir -r backend/requirements.txt && npm install --prefix frontend"
    startCommand: "foreman start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fpl-db
          property: connectionString
