services:
  - type: web
    name: fpl-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:8000 'app:create_app()'"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fpl-db
          property: connectionString
